name: Validar script con ShellCheck

on:
  push:
    branches:
      - main

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Ejecutar ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: '.'
